"""initial_schema_baseline

Revision ID: 850b05bae804
Revises: 
Create Date: 2026-03-17 17:53:31.614905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850b05bae804'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_event_id', table_name='audit_logs')
    op.drop_index('idx_events_org_id', table_name='events')
    op.drop_index('idx_events_slug', table_name='events')
    op.drop_index('idx_events_status', table_name='events')
    op.drop_index('idx_reg_forms_event_id', table_name='registration_forms')
    op.drop_index('idx_reg_links_event_id', table_name='registration_links')
    op.drop_index('idx_reg_links_short_code', table_name='registration_links')
    op.drop_index('idx_tickets_event_id', table_name='tickets')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint('users_org_id_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_org_id_email_key', 'users', ['org_id', 'email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('idx_tickets_event_id', 'tickets', ['event_id'], unique=False)
    op.create_index('idx_reg_links_short_code', 'registration_links', ['short_code'], unique=False)
    op.create_index('idx_reg_links_event_id', 'registration_links', ['event_id'], unique=False)
    op.create_index('idx_reg_forms_event_id', 'registration_forms', ['event_id'], unique=False)
    op.create_index('idx_events_status', 'events', ['status'], unique=False)
    op.create_index('idx_events_slug', 'events', ['slug'], unique=False)
    op.create_index('idx_events_org_id', 'events', ['org_id'], unique=False)
    op.create_index('idx_audit_logs_event_id', 'audit_logs', ['event_id'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
